version: "3"
services:
  app:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8080
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
